### ISSUE TITLE
Twitter Lists Redux Google Chrome extension is not working

### ISSUE THREAD

**Issue by KC20cy** [tomitm/lists#10]
@tomitm 
Hi there,

I just installed Twitter Lists Redux Google Chrome extension on Iron chromium browser on my laptop, but the extension does not seem to be working, please advise, thanks.

Regards,

KC

**Comment by tomitm** [comment]
Hi KC! Can you give me more details about which part isn't working? The sidebar, the popup, or both? Can you provide a screenshot? You can drag and drop or paste an image in the comment box here.

To clarify, the button in Chrome's address bar doesn't do anything. [You wouldn't be the first to think that](https://twitter.com/joedale/status/904361636395352064), so I should add some sort of message in there to explain. Chrome puts the button there these days regardless of if it's useful or not, sorry.

Twitter Lists Redux is designed to be a seamless experience on Twitter that blends right in without getting in the way. All it does is it adds your lists to the left sidebar on twitter.com and also on the card that pops up when you hover over someone's name. The [two screenshots here](https://chrome.google.com/webstore/detail/twitter-lists-redux/kcincllgjifchjihkklkcfdniofcjahb) demonstrate this.

Let me know if you're not seeing those, and I'll see what I can do for you.

**Comment by KC20cy** [comment]
@tomitm 

Hi there,
After reading your reply, I tried to visit the Home web page of my Twitter profile, now I get the point about what this extension will do, and I saw a list shown at the left side of my Twitter profile.  Thank you for your attention and thank you for your works.

Regards,

KC

**Comment by tomitm** [comment]
Glad that helped. Enjoy! 🎉
