### ISSUE TITLE
Need Taller Panel + Scroll Past End Closes Issue

### ISSUE THREAD

**Issue by PowerWeb5** [tomitm/lists#11]
Can you please add option to customize height of the box. I have to scroll down about 10 pages to find the list I want.
Also, I can't use mousewheel or else dialog closes once go beyond the end and have to start all over again.
I could really use full screen height.
Also, as quick workaround, can you tell me the CSS that controls height so I can create user style for that?

**Comment by tomitm** [comment]
Looks like I missed this a while ago, sorry!

I haven't really optimized the extension for a large amount of lists since I personally don't have that many.

If you want to setup a user style, you should be able to set the height on `.Lists.component ul`.
