### ISSUE TITLE
No longer working...

### ISSUE THREAD

**Issue by Jonny-Mnemonic** [tomitm/lists#14]
The only feature currently working is the LIST in the left pane of the Twitter TL view.

Hovering and selecting lists no longer works.  Hovering does bring up the twitter lists but for some reason the selection boxes are no longer accepting clicks to place checkmarks in the list selection boxes...

**Comment by DDurling** [comment]
Confirmed this doesn't work on Chrome OS Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by tomitm** [comment]
@Jonny-Mnemonic @DDurling Sorry I missed this earlier. Is this still an issue for you?

I haven't noticed any issues in the time you posted this, and it currently doesn't appear to be an issue for me on Chrome 68 beta. I also don't believe I've seen any errors about this captured in Sentry. 🤔

Can you tell me if you see any network failures or console errors in developer tools (F12)? There would be a POST request to /members to add (and DELETE to remove), both return an empty object as a response when successful. Thanks
