### ISSUE TITLE
List management assistance?

### ISSUE THREAD

**Issue by estaub** [tomitm/lists#16]
Scenario: I've created some lists, and maybe three-quarters of my followees are on them.  How do I quickly add the other followees to lists as appropriate?  

One simple UI is a matrix like what http://twitlistmanager.com/index.php used to do.  

If the API doesn't support list editing in this context, note that even a read-only matrix would be extremely helpful.

**Comment by Lizx555** [comment]
I should be grateful if you would kindly fix this.

**Comment by tomitm** [comment]
Sorry, mass management is not in the scope of this extension.

It deviates a bit too far from the intended simplicity of this extension, and seems more suited for a purpose-built tool, like the example you gave.
