### ISSUE TITLE
Is there an update for New Twitter?

### ISSUE THREAD

**Issue by KC20cy** [tomitm/lists#17]
Hi there, thanks for your Chrome extension, is there an update for new Twitter? Thanks.

**Comment by tomitm** [comment]
New Twitter uses generated CSS class names and React, which complicates things on this end.

While a handful of elements seem to have an `id` or `data-testid` attribute, they're insufficient to use as targets for injecting the lists. Even though class names may be deterministic and not change as often, that still leaves a chance for a breaking change one day. This isn't great for users, and keeping CSS selectors updated is not a particular maintenance task I want to keep up with either.

Unfortunately I don't think this is happening anytime soon.

**Comment by KC20cy** [comment]
Copy that, I am not a man of coding, so some of your reply is difficult for me..., but, thank you for your previous works anyway.

**Comment by tomitm** [comment]
Oh, sorry!

On old Twitter, it was easy to find the sidebar with a plain name so I knew where to put the lists. New Twitter has random naming which can possibly change when they make an update, which makes the sidebar almost like a moving target.

If I tried to use the random names, the extension would randomly break one day until I updated it. And that would keep happening. That's not really the kind of user experience I think is acceptable, so I can't do this until I can find a more stable solution.

Hope that helps explain things.

**Comment by KC20cy** [comment]
Perhaps if you make a dropdown list button of the list which you might find it easier to find a place to fit(my guess, I am not a coder) and it will still works for user like me.

**Comment by tomitm** [comment]
The layout itself isn't an issue, so it can still look the same, rather it's like finding an address on a map.

All the street names are randomized weekly, so even though you know where your destination is off the top of your head, it's hard to write down directions for it for someone else to find, and all the landmarks are randomized too. You'd have to update the directions every time the street names changed, which isn't really viable long-term.
