### ISSUE TITLE
Cannot add user to list in newest version of Chrome

### ISSUE THREAD

**Issue by lologardens** [tomitm/lists#18]
I click on my list and it quickly shows processing circle and then it goes away without checking the box.

Ive tried on mulitple computers.

Chrome Version 74.0.3729.108

**Comment by QFortuna** [comment]
I have the same issue on 74.0.3729.108

![Apr-27-2019 ](https://user-images.githubusercontent.com/29421302/56850359-2d2ca200-690a-11e9-9369-b027b6299bb9.gif)

**Comment by tomitm** [comment]
Thanks for reporting this! 🙌

Looks like Twitter finally tightened up their API security at some point, which is preventing POST requests from extensions. May not be a quick fix as they're checking the `Origin` header now, which is managed by the browser.

**Comment by lologardens** [comment]
Twitter's always causing problems ;)
Appreciate any fix but understand if you are too busy to tackle right away.
Will keep a look out.
Thanks again!

**Comment by tomitm** [comment]
Looks like this was [a Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=944704), as this is now back to working! 🎉

This bug appears to only affect Chrome 74; <= 73 and >= 75 should be working.
