### ISSUE TITLE
Main Functionality Broken

### ISSUE THREAD

**Issue by BluesGator** [tomitm/lists#19]
On hover the lists pop up but can't check box to add someone to a list. Are you going to be able to fix this or is the party over for this extension?

**Comment by tomitm** [comment]
Party _may_ be coming to an end here, not sure yet. I've noted some details in the other issue, #18.

**Comment by tomitm** [comment]
Quick update, party's back on! Chrome 74 is affected, so upgrade to Chrome 75 or later and you're set.

Details are in the other issue if you're curious.

**Comment by BluesGator** [comment]
You rock, Tomi!


[image: --]

Peter Gaeta
[image: https://]about.me/petergaeta
<https://about.me/petergaeta?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
