### ISSUE TITLE
💉 #Enhancement As a desktop user I want to order lists alphabetically so I can find them

### ISSUE THREAD

**Issue by ldexterldesign** [tomitm/lists#5]
https://twitter.com/ldexterldesign/status/709544033073414145 > https://github.com/tomitm/lists/issues/4#issuecomment-221080890

**Comment by ldexterldesign** [comment]
BUMP

**Comment by tomitm** [comment]
While this is pretty simple, it's also a bit disruptive as it changes how people are used to seeing/using their lists. I'm planning on adding this as a preference to avoid that disruption.

I just haven't had a chance to sit down and implement the preferences part yet. Don't worry, haven't forgotten about this! 😄

**Comment by ldexterldesign** [comment]
Thanks for reply

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
> Currently I've only applied styling to that add/remove modal, but I'll see if I can detect when it opens so I can sort the list as well.
- https://github.com/tomitm/lists/issues/4#issuecomment-230349452

Look forward to this addition!

Yours hopefully

**Comment by tomitm** [comment]
This has been implemented in #7! Will be releasing an update to the extension later this week. 🎉

**Comment by ldexterldesign** [comment]
Apologies for delay

Cheers for implementing this enhancement - good work, much appreciated! 👏

Kind thanks

**Comment by tomitm** [comment]
@ldexterldesign Glad I could help! 🙋
